# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test *.Tests/*.Tests.csproj --collect:"XPlat Code Coverage
  displayName: 'Run test'
- task: reportgenerator@5
  inputs:
    reports: '*.Tests/TestResults/**/coverage.cobertura.xml'
    targetdir: 'coveragereport'
    sourcedirs: '*.Tests'
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'access-forge'



