name: deploy-book

on:
  push:
    branches:
    - docs

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: cache executed notebooks
      uses: actions/cache@v4
      with:
        path: _build/.jupyter_cache
        key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}
    - name: Build the book
      run: |
        jupyter-book build .
    - name: add and commit userguide to gh-page
      run: |
         git config --global user.name 'Adexandria'
         git config --global user.email 'adeolaaderibigbe09@gmail.com'
         git checkout --orphan docs-deploy
         git rm -rf .
         git add _build/html/*
         git commit -m "Add user guide"
         git config pull.rebase false 
         git pull origin gh-pages --allow-unrelated-histories
         git push origin docs-deploy:gh-pages
