# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths-ignore:
    - '.gitignore'
    
  workflow_dispatch: 

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    pull-requests: write
    deployments: write
    contents: write
    checks: read 

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Deploy to git pages
        id: deployment
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          folder: Documentation/project
          config_file: Documentation/Doxyfile.config
          doxygen_version: 1.9.5
          github_token: ${{ secrets.GITHUB_TOKEN }}
     

